on:
  push:
    branches:
      - main

name: Release main please

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-20.04
    steps:
      - uses: kalosisz/release-please-action@3d397b8e7d8eb769b5948806db2dee642b1f79ad
        id: release
        with:
          release-type: python
          package-name: workshopper
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Complete
        run: echo Is draft
        if: ${{ steps.release.outputs.draft }}
